_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 63
                - 71
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 55
                - 63
                - 71
                - 103
                - 106
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.18
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 6
            "12": 0.19.7
            "13": linux-x86_64
K:
    value: 1000
base_path:
    value: data_and_model/
beta:
    value: 0.5
beta1:
    value: 0.9
beta2:
    value: 0.999
config_name:
    value: config_sdpo_gosai.yaml
config_path:
    value: configs_gosai
eps:
    value: 1e-08
eval_every:
    value: 20
generator:
    value: rkl
lr:
    value: 0.0003
model_path:
    value: mdlm/outputs_gosai/pretrained.ckpt
num_epochs:
    value: 1
ref_model_path:
    value: mdlm/outputs_gosai/pretrained.ckpt
save_path:
    value: results.pt
seed:
    value: 0
verbose:
    value: true
wandb:
    value: true
weight_decay:
    value: 0
